name: Cache Dependencies Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-6f65bef

      - name: Install dependencies (only if cache miss)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: prime-cache-6f65bef
        run: echo "Cache hit/miss result: ${{ steps.cache-deps.outputs.cache-hit }}"

      - name: Verify installation (demo step)
        run: python -c 'import numpy; print("Dependencies loaded successfully!")'

